.TH OpenGLWidgetFigure  1  "November 12, 2023" "version 1" "General Commands Manual"

.SH NAME
OpenGLWidgetFigure 

.SH SYNOPSIS
.B OpenGLWidgetFigure 

.SH DESCRIPTION
.B OpenGLWidgetFigure  
using QT & OpenGL to render a model of a teapot.

.SH OPTIONS
.PP
This program does not accept any command line options.

.PP
This manual page was written by
.MT 812897519@\:qq.com
 Xu ShiWen
.ME
for the Debian project (and may be used by others).
